# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(888, 616)
        self.product_image = QtWidgets.QLabel(Form)
        self.product_image.setGeometry(QtCore.QRect(630, 30, 241, 211))
        self.product_image.setText("")
        self.product_image.setPixmap(QtGui.QPixmap("./images/10.png"))
        self.product_image.setObjectName("product_image")
        self.product_desc = QtWidgets.QTextEdit(Form)
        self.product_desc.setGeometry(QtCore.QRect(280, 120, 331, 111))
        self.product_desc.setReadOnly(True)
        self.product_desc.setObjectName("product_desc")
        self.product_name = QtWidgets.QLabel(Form)
        self.product_name.setGeometry(QtCore.QRect(560, 100, 49, 16))
        self.product_name.setObjectName("product_name")
        self.bidders_list = QtWidgets.QTableView(Form)
        self.bidders_list.setGeometry(QtCore.QRect(280, 371, 601, 241))
        self.bidders_list.setObjectName("bidders_list")
        self.bidder_id = QtWidgets.QTextEdit(Form)
        self.bidder_id.setGeometry(QtCore.QRect(290, 270, 181, 31))
        self.bidder_id.setObjectName("bidder_id")
        self.bidder_name = QtWidgets.QTextEdit(Form)
        self.bidder_name.setGeometry(QtCore.QRect(290, 310, 181, 31))
        self.bidder_name.setObjectName("bidder_name")
        self.bidder_price = QtWidgets.QSpinBox(Form)
        self.bidder_price.setGeometry(QtCore.QRect(500, 310, 151, 31))
        self.bidder_price.setObjectName("bidder_price")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(500, 290, 81, 16))
        self.label_3.setObjectName("label_3")
        self.bid_validation = QtWidgets.QPushButton(Form)
        self.bid_validation.setGeometry(QtCore.QRect(710, 310, 75, 31))
        self.bid_validation.setObjectName("bid_validation")
        self.product_list = QtWidgets.QListView(Form)
        self.product_list.setGeometry(QtCore.QRect(0, 0, 261, 621))
        self.product_list.setObjectName("product_list")

        self.product_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listModel = QtGui.QStandardItemModel()
        self.product_list.setModel(self.listModel)
        self.product_list.clicked[QtCore.QModelIndex].connect(self.openSelectedClickListener)
        item = QtGui.QStandardItem(f'test')
        self.listModel.appendRow(item)

        # fill the list view with the database names
        # send a request to get all of the names

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.product_desc.setPlaceholderText(_translate("Form", "Description du produit"))
        self.product_name.setText(_translate("Form", "NAME"))
        self.bidder_id.setPlaceholderText(_translate("Form", "Entrez votre id"))
        self.bidder_name.setPlaceholderText(_translate("Form", "Entrez votre nom"))
        self.label_3.setText(_translate("Form", "Prix  proposé"))
        self.bid_validation.setText(_translate("Form", "Valider"))
    def openSelectedClickListener(self, index):
        item = self.listModel.itemFromIndex(index)
        self.product_name.setText(item.text())
        ## update all the info from the database
        #get requests loop


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
